FROM centos:7
ENV container docker

#cleanup to enable systemd
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
    systemd-tmpfiles-setup.service ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /etc/systemd/system/*.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*;

#Install build environment dependencies
RUN yum update -y && \
    yum install -y epel-release make rpmbuild rpmdevtools && \
    yum install -y python3-sphinx python3-devel python3-six python3-setuptools && \
    # Fix to build python-dateutil
    ln -s /usr/bin/sphinx-build-3 /usr/bin/sphinx-build && \
    yum clean all && \
    mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS} && \
    echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros

# Copy code to /app
COPY . /app

#Build RPMs
RUN cd /app && \
    make dist && \
    # elmond
    mv perfsonar-elmond-*.tar.gz ~/rpmbuild/SOURCES/ && \
    rpmbuild -bs perfsonar-elmond.spec && \
    rpmbuild -ba perfsonar-elmond.spec && \
    # python-libraries
    mv python-dateutil/dateutil-*.tar.gz ~/rpmbuild/SOURCES/ && \
    rpmbuild -bs python-dateutil/python-dateutil.spec && \
    rpmbuild -ba python-dateutil/python-dateutil.spec && \
    mv python-elasticsearch/elasticsearch-*.tar.gz ~/rpmbuild/SOURCES/ && \
    rpmbuild -bs python-elasticsearch/python-elasticsearch.spec && \
    rpmbuild -ba python-elasticsearch/python-elasticsearch.spec

#shared volumes
VOLUME /sys/fs/cgroup

CMD ["/usr/sbin/init"]